### ISSUE TITLE
Text Input memory

### ISSUE THREAD

**Issue by Gaalee** [ExterminatorX99/MagicStorageExtra#52]
Hi, I love your version of MS but one thing that i find a really big downgrade, is that the input text, to search item don't clear himself when you close the storage. Can we have a setting to toggle this feature please ? 

Thanks.

**Comment by studkid** [comment]
If the issue you have is related to how long it takes to clear the search tab, as quick work around you can right click the search box to instantly clear it (this actually works with most text fields found in various mods).  Maybe it's still a huge inconvenience to you but I figured I might as well mention that functionality exists since I'm not sure if that's common common knowledge.
